apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wall-color-postgres
  namespace: wall-color
spec:
  instances: 2

  imageName: docker.io/postgres:18-alpine
  bootstrap:
    initdb:
      # TODO: avoid hardcode with Kustomize or Helm
      #   + de-duplicate database with value from shared-config.yaml
      database: app
      owner: admin
      secret:
        name: wall-color-db-secret
      postInitApplicationSQLRefs:
        configMapRefs:
          # this needs `kubectl create configmap wall-color-postgres-schema --from-file=../seed/00_schema.sql -n wall-color`
          - name: wall-color-postgres-schema
            key: 00_schema.sql
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # Optional but recommended
  primaryUpdateStrategy: unsupervised
