apiVersion: v1
kind: ConfigMap
metadata:
  name: wall-color-config
  namespace: wall-color
data:
  POSTGRES_DB: {{ .Values.database.name }}
  TOKEN_MAX_AGE_SECONDS: "{{ .Values.tokenMaxAgeInSeconds }}"