name: Backend CI

on:
  pull_request:
    paths:
      - "color-manager/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: color-manager

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
      - name: Do linting
        run: mvn verify --batch-mode --no-transfer-progress -Ddo.linting

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v5
        with:
          maven-args: '-ntp'
          ignore-maven-wrapper: true
          directory: color-manager

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: color-manager

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
      - name: init project
        working-directory: .
        run: ./project-init.sh
      - name: Do tests
        run: mvn verify --batch-mode --no-transfer-progress
